# Presentation Title
title: Jekyll-Flowtimejs

# Presentation Owner/author
owner:
  name:           Pham Ngoc Hung
  email:          pnhung177@drupalex.net
  twitter:        pnhung177
  facebook:       pnhung177
  github:         pnhung177
  google_plus:    https://plus.google.com/u/3/115458186421626071505
  description: 	Presentation = Jekyll + Flowtimejs + Markdown

# Presentation Framework
flowtime_path: flowtime.js/

flowtime_options:
  navigation_enabled: true
  horizontal_direction: false

# Presentation theme
theme_default: flowtime.js/css/themes/default.css
theme_custom: assets/css/custom.css

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-54128248-1

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Ho_Chi_Minh
highlighter: pygments
markdown:    kramdown

include: [".htaccess"]
exclude: ["resources", "*.gliffy", "*.xcf", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
